// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chainstate.proto

/*
Package blockchain is a generated protocol buffer package.

It is generated from these files:
	chainstate.proto

It has these top-level messages:
	EntryHeader
	BlockEntry
	BlockHeader
	BlockContent
	Signature
	PeerState
	PeerInfo
	State
	StateResponse
	WormPayload
*/
package blockchain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryHeader struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *EntryHeader) Reset()                    { *m = EntryHeader{} }
func (m *EntryHeader) String() string            { return proto.CompactTextString(m) }
func (*EntryHeader) ProtoMessage()               {}
func (*EntryHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EntryHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BlockEntry struct {
	Hash    []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *BlockEntry) Reset()                    { *m = BlockEntry{} }
func (m *BlockEntry) String() string            { return proto.CompactTextString(m) }
func (*BlockEntry) ProtoMessage()               {}
func (*BlockEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockEntry) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockEntry) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type BlockHeader struct {
	RootHash []byte `protobuf:"bytes,1,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	PrevHash []byte `protobuf:"bytes,2,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BlockHeader) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *BlockHeader) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

type BlockContent struct {
	RootHash []byte   `protobuf:"bytes,1,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	PrevHash []byte   `protobuf:"bytes,2,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Content  [][]byte `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
}

func (m *BlockContent) Reset()                    { *m = BlockContent{} }
func (m *BlockContent) String() string            { return proto.CompactTextString(m) }
func (*BlockContent) ProtoMessage()               {}
func (*BlockContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BlockContent) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *BlockContent) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *BlockContent) GetContent() [][]byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Signature struct {
	R []byte `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Signature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Signature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type PeerState struct {
	Id          string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	EntryHashes [][]byte   `protobuf:"bytes,2,rep,name=entryHashes,proto3" json:"entryHashes,omitempty"`
	RootHash    []byte     `protobuf:"bytes,3,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	PrevHash    []byte     `protobuf:"bytes,4,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Epoch       uint64     `protobuf:"varint,5,opt,name=epoch" json:"epoch,omitempty"`
	Signature   *Signature `protobuf:"bytes,6,opt,name=signature" json:"signature,omitempty"`
	// Only for worm interaction
	// TODO solve this differently
	HttpAddr string `protobuf:"bytes,7,opt,name=httpAddr" json:"httpAddr,omitempty"`
}

func (m *PeerState) Reset()                    { *m = PeerState{} }
func (m *PeerState) String() string            { return proto.CompactTextString(m) }
func (*PeerState) ProtoMessage()               {}
func (*PeerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PeerState) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PeerState) GetEntryHashes() [][]byte {
	if m != nil {
		return m.EntryHashes
	}
	return nil
}

func (m *PeerState) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *PeerState) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *PeerState) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *PeerState) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PeerState) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

type PeerInfo struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Epoch    uint64 `protobuf:"varint,2,opt,name=epoch" json:"epoch,omitempty"`
	RootHash []byte `protobuf:"bytes,3,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
}

func (m *PeerInfo) Reset()                    { *m = PeerInfo{} }
func (m *PeerInfo) String() string            { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()               {}
func (*PeerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PeerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PeerInfo) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *PeerInfo) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

type State struct {
	Peers          map[string]*PeerInfo `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MissingEntries [][]byte             `protobuf:"bytes,2,rep,name=missingEntries,proto3" json:"missingEntries,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *State) GetPeers() map[string]*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *State) GetMissingEntries() [][]byte {
	if m != nil {
		return m.MissingEntries
	}
	return nil
}

type StateResponse struct {
	Peers   []*PeerState  `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
	Entries []*BlockEntry `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StateResponse) GetPeers() []*PeerState {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *StateResponse) GetEntries() []*BlockEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type WormPayload struct {
	Blocks map[uint64]*BlockHeader `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *WormPayload) Reset()                    { *m = WormPayload{} }
func (m *WormPayload) String() string            { return proto.CompactTextString(m) }
func (*WormPayload) ProtoMessage()               {}
func (*WormPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *WormPayload) GetBlocks() map[uint64]*BlockHeader {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*EntryHeader)(nil), "blockchain.EntryHeader")
	proto.RegisterType((*BlockEntry)(nil), "blockchain.BlockEntry")
	proto.RegisterType((*BlockHeader)(nil), "blockchain.BlockHeader")
	proto.RegisterType((*BlockContent)(nil), "blockchain.BlockContent")
	proto.RegisterType((*Signature)(nil), "blockchain.Signature")
	proto.RegisterType((*PeerState)(nil), "blockchain.PeerState")
	proto.RegisterType((*PeerInfo)(nil), "blockchain.PeerInfo")
	proto.RegisterType((*State)(nil), "blockchain.State")
	proto.RegisterType((*StateResponse)(nil), "blockchain.StateResponse")
	proto.RegisterType((*WormPayload)(nil), "blockchain.WormPayload")
}

func init() { proto.RegisterFile("chainstate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0xe5, 0xa4, 0x69, 0xd7, 0x93, 0xbe, 0xd3, 0x64, 0x6d, 0x2f, 0x51, 0xc5, 0x45, 0x08,
	0x12, 0x54, 0x20, 0x2a, 0x94, 0xdd, 0xa0, 0x71, 0x05, 0x68, 0xd2, 0x90, 0x10, 0x9a, 0xb2, 0x0b,
	0x6e, 0xf1, 0x9a, 0xc3, 0x12, 0xad, 0xb3, 0x23, 0xdb, 0x9b, 0xd4, 0x2f, 0xc3, 0x97, 0xe0, 0xeb,
	0xf0, 0x61, 0x90, 0xed, 0xfc, 0x71, 0x5b, 0xb4, 0x0b, 0xee, 0x72, 0x9c, 0xe7, 0x3c, 0xe7, 0x77,
	0x9e, 0xc6, 0x85, 0xa3, 0x55, 0xc5, 0x6a, 0xae, 0x34, 0xd3, 0xb8, 0x6c, 0xa4, 0xd0, 0x82, 0xc2,
	0xf5, 0x5a, 0xac, 0x6e, 0xed, 0x71, 0xf6, 0x0c, 0xe2, 0x73, 0xae, 0xe5, 0xe6, 0x02, 0x59, 0x89,
	0x92, 0x52, 0x18, 0x55, 0x4c, 0x55, 0x09, 0x49, 0xc9, 0x62, 0x56, 0xd8, 0xe7, 0xec, 0x0c, 0xe0,
	0xa3, 0x69, 0xb0, 0xba, 0xbf, 0x29, 0x68, 0x02, 0x93, 0x95, 0xe0, 0x1a, 0xb9, 0x4e, 0x02, 0x7b,
	0xdc, 0x95, 0xd9, 0x39, 0xc4, 0xb6, 0xb7, 0xb5, 0x9f, 0xc3, 0x81, 0x14, 0x42, 0x5f, 0x0c, 0x06,
	0x7d, 0x6d, 0xde, 0x35, 0x12, 0x1f, 0xec, 0x3b, 0xe7, 0xd2, 0xd7, 0xd9, 0x77, 0x98, 0x59, 0x9b,
	0x4f, 0xce, 0xf6, 0x5f, 0x7d, 0x7c, 0xd0, 0x30, 0x0d, 0x7d, 0xd0, 0x97, 0x30, 0xbd, 0xaa, 0x6f,
	0x38, 0xd3, 0xf7, 0x12, 0xe9, 0x0c, 0x88, 0x6c, 0x7d, 0x89, 0x34, 0x95, 0x6a, 0x9d, 0x88, 0xca,
	0x7e, 0x13, 0x98, 0x5e, 0x22, 0xca, 0x2b, 0x13, 0x28, 0x3d, 0x84, 0xa0, 0x2e, 0xad, 0x74, 0x5a,
	0x04, 0x75, 0x49, 0x53, 0x88, 0xd1, 0xc6, 0xc9, 0x54, 0x85, 0xa6, 0xcb, 0x0c, 0xf1, 0x8f, 0xb6,
	0xd0, 0xc3, 0x47, 0xd0, 0x47, 0x3b, 0xe8, 0xc7, 0x10, 0x61, 0x23, 0x56, 0x55, 0x12, 0xa5, 0x64,
	0x31, 0x2a, 0x5c, 0x41, 0x4f, 0x61, 0xaa, 0x3a, 0xec, 0x64, 0x9c, 0x92, 0x45, 0x9c, 0x9f, 0x2c,
	0x87, 0x9f, 0x77, 0xd9, 0xef, 0x54, 0x0c, 0x3a, 0x33, 0xa6, 0xd2, 0xba, 0xf9, 0x50, 0x96, 0x32,
	0x99, 0x58, 0xf4, 0xbe, 0xce, 0xbe, 0xc0, 0x81, 0xd9, 0xee, 0x33, 0xff, 0x21, 0xf6, 0x96, 0xeb,
	0x11, 0x02, 0x1f, 0xe1, 0x91, 0x85, 0xb2, 0x5f, 0x04, 0x22, 0x17, 0x54, 0x0e, 0x51, 0x83, 0x28,
	0x55, 0x42, 0xd2, 0x70, 0x11, 0xe7, 0x4f, 0xb7, 0x20, 0xed, 0xb7, 0x69, 0xc6, 0x2a, 0xfb, 0x8d,
	0x15, 0x4e, 0x4a, 0x5f, 0xc0, 0xe1, 0x5d, 0xad, 0x54, 0xcd, 0x6f, 0xcc, 0x71, 0xdd, 0xe7, 0xb9,
	0x73, 0x3a, 0xff, 0x0a, 0x30, 0x34, 0xd3, 0x23, 0x08, 0x6f, 0x71, 0xd3, 0x62, 0x9b, 0x47, 0xfa,
	0x0a, 0xa2, 0x07, 0xb6, 0xbe, 0x47, 0xcb, 0x1d, 0xe7, 0xc7, 0xfe, 0xec, 0x6e, 0xd9, 0xc2, 0x49,
	0xce, 0x82, 0x77, 0x24, 0xe3, 0xf0, 0x9f, 0x45, 0x2a, 0x50, 0x35, 0x82, 0x2b, 0xa4, 0xaf, 0xb7,
	0xe1, 0x4f, 0x76, 0x0d, 0x9c, 0xba, 0xa5, 0x7e, 0x0b, 0x13, 0xf4, 0x70, 0xe3, 0xfc, 0x7f, 0x5f,
	0x3e, 0xdc, 0xa4, 0xa2, 0x93, 0x65, 0x3f, 0x09, 0xc4, 0xdf, 0x84, 0xbc, 0xbb, 0x64, 0x9b, 0xb5,
	0x60, 0x25, 0x7d, 0x0f, 0x63, 0xdb, 0xd1, 0xcd, 0x7b, 0xee, 0x1b, 0x78, 0x42, 0x67, 0xd6, 0x66,
	0xd6, 0xb6, 0xcc, 0x8b, 0xf6, 0xc6, 0xed, 0xa7, 0x31, 0x72, 0x69, 0xbc, 0xd9, 0x4e, 0xe3, 0xc9,
	0x1e, 0x9d, 0xbb, 0xab, 0x5e, 0x20, 0xd7, 0x63, 0xfb, 0xbf, 0x71, 0xfa, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x9b, 0x0f, 0x89, 0x75, 0x4b, 0x04, 0x00, 0x00,
}
